apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: viktor-guestbook-argocd
  namespace: openshift-gitops 
spec:
  project: default
  source:
    repoURL: https://github.com/TheSuperSwan/viktor-guestbook-argocd
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: grupp5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
